title: гера волобуев 
permalink: /blog/:slug

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: ./assets/css/
  style: compressed

markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1

collections:
  projects:
    output: true
  note_translations:
    output: false

exclude:
  - CONTINUITY.md
  - node_modules
  - package.json
  - package-lock.json
  - test
